apiVersion: v1
kind: Service
metadata:
    name: learn-k8s
spec:
    selector:
        app: learn-k8s
    ports:
        - protocol: "TCP"
          port: 6000
          targetPort: 5000
    type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: learn-k8s
spec:
    selector:
        matchLabels:
            app: learn-k8s
    replicas: 4
    template:
        metadata:
            labels:
                app: learn-k8s
        spec:
            containers:
                - name: learn-k8s
                  image: learn-k8s:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 5000
